lb-db:
  image: tutum/haproxy:0.1
  environment:
    - BACKEND_PORTS=28015
    - MODE=tcp
  links:
    - rethinkdb
  ports:
    - "8082:1936"
    - "28015:80"
rethinkdb:
  image: anapsix/rethinkdb:latest
  ports:
    - "8080:8080"
ws:
  image: siboulet/websockify
  command: "./run 815 rethinkdb:80"
  ports:
    - "815:815"

