# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e800341a22ce5c8fa03fe59b3309d63d15617dc9ffcbc35f4e3cf4a4b5969b3e38fe1adfbfcef990bc8450e459cf2835e65eea82492af9f501b9c9832320ac9

test:
  secret_key_base: 2e2d5c27defd12a848d67049158f3ba0bd2913f5a44e57a0f483a2d170ec9d55c4d38482b81d1cce41903b641295dd3b8eab2d1e636fb11abb5ffc2625fdb7f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
